
name: Run Hotel Video Pipeline

on:
  push:
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  run-python-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies (if any)
        run: pip install -r requirements.txt || true

      - name: Run ABASE.py
        run: python ABASE.py

      - name: Run ASHORT.py
        run: python ASHORT.py

      - name: Sleep after ASHORT.py
        run: sleep 70

      - name: Run ASHORT1.py
        run: python ASHORT1.py

      - name: Sleep after ASHORT1.py
        run: sleep 70

      - name: Run ASHORT2.py
        run: python ASHORT2.py

      - name: Sleep after ASHORT2.py
        run: sleep 70

      - name: Run ASHORT3.py
        run: python ASHORT3.py

      - name: Sleep after ASHORT3.py
        run: sleep 70

      - name: Run ASHORT4.py
        run: python ASHORT4.py

      - name: Sleep after ASHORT4.py
        run: sleep 70

      - name: Run ABASE1.py (Commit logic)
        run: python ABASE1.py
