
name: Run ASHORT LINK + Scripts Safely

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours

jobs:
  run-ashort-sequence:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade typing_extensions
          pip install \
            google-genai==0.2.2 \
            pydantic==2.6.4 \
            mediapipe \
            opencv-python \
            numpy \
            moviepy \
            spleeter

      - name: Install yt-dlp
        run: |
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp

      - name: Run ASHORT_LINK.py (handles link selection)
        env:
          GEMINI_API: ${{ secrets.GEMINI_API }}
        run: python ASHORT_LINK.py

      - name: Wait before ASHORT1
        run: sleep 90

      - name: Run ASHORT1.py
        env:
          GEMINI_API: ${{ secrets.GEMINI_API }}
        run: python ASHORT1.py

      - name: Wait before ASHORT2
        run: sleep 90

      - name: Run ASHORT2.py
        env:
          GEMINI_API: ${{ secrets.GEMINI_API }}
        run: python ASHORT2.py

      - name: Wait before ASHORT3
        run: sleep 90

      - name: Run ASHORT3.py
        env:
          GEMINI_API: ${{ secrets.GEMINI_API }}
        run: python ASHORT3.py

      - name: Wait before ASHORT4
        run: sleep 90

      - name: Run ASHORT4.py
        env:
          GEMINI_API: ${{ secrets.GEMINI_API }}
        run: python ASHORT4.py

      - name: Commit ASHORT.txt if Vid/product.txt contains no or No
        run: |
          if grep -iq '^no$' Vid/product.txt; then
            git config --global user.name "yt-bot"
            git config --global user.email "yt-bot@example.com"

            git stash --include-untracked
            git pull --rebase origin main
            git stash pop || true

            git add ASHORT.txt
            git diff --cached --quiet || git commit -m "Update ASHORT.txt for product no - $(date)"
            git push
          else
            echo "No 'no' found in Vid/product.txt — skipping commit."
