
name: Combine ASMR Shorts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 06:00 UTC

jobs:
  combine-asmr-shorts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Combine and sort ASMR_SHORT files
        run: |
          # Combine all ASMR_SHORT*.txt files
          cat ASMR_SHORT*.txt > combined.txt

          # Extract valid 2-line blocks and sort by views (cleaning commas)
          awk '
            /^.*views \|/ {
              viewsStr = $1
              gsub(",", "", viewsStr)
              views = viewsStr + 0
              title = $0
              getline
              if ($0 ~ /^https:\/\/www\.youtube\.com\/watch\?v=/) {
                print views "|" title "|" $0
              }
            }
          ' combined.txt | sort -nr -k1,1 | awk -F"|" '{ print $2 ORS $3 "\n" }' > ASMR_ALL.txt

      - name: Commit ASMR_ALL.txt
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add ASMR_ALL.txt
          git commit -m "Update ASMR_ALL.txt with sorted ASMR shorts" || echo "No changes to commit"
          git push
