name: Classify Products Daily

on:
  schedule:
    # Runs every day at 7:00 AM UTC
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  classify:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install gitpython

      # Step 4: Run the Python script (prd_classifier.py)
      - name: Run prd_classifier.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          python prd_classifier.py

      # Step 5: Upload any artifacts if needed (optional, adjust as needed)
      - name: Upload classified products as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: classified-products
          path: |
            c.txt
            p.txt

      # Step 6: (Optional) Download artifacts in case you want to use them later
      # - name: Download classified products artifact (if needed)
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: classified-products
