name: Run Product Classifier

on:
  schedule:
    - cron: "5 0 * * *"  # Runs daily at 12:05 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  classify_products:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all files are pulled

      - name: Verify products.txt exists
        run: ls -l products.txt || echo "⚠️ products.txt not found, will attempt to fetch."

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install requests

      - name: Run Product Classifier (50 products)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python prd_classifier.py
