name: Product Classification

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  classify_products:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Unlock SSH Key
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add ~/.ssh/id_rsa

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run product classifier script
        run: |
          python prd_classifier.py --limit 50

      - name: Push changes if any
        run: |
          git config --global user.email "Starches171@gmail.com"
          git config --global user.name "Starches71"
          git add .
          git commit -m "Automated product classification update" || echo "No changes to commit"
          git push git@github.com:Starches71/71.git main
