
name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - main  # Deploys when changes are pushed to the main branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages  # This specifies the environment for GitHub Pages deployment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Pages directory
        run: |
          mkdir gh-pages
          cp index.html gh-pages/
          cp style.css gh-pages/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages  # This deploys the specific directory containing index.html and style.css
