name: FFmpeg Video Processing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  video-processing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up FFmpeg
      run: |
        sudo apt update
        sudo apt install -y ffmpeg

    - name: Run FFmpeg command
      run: |
        ffmpeg -f lavfi -t 10 -i color=c=black:s=1280x720:r=30 -f lavfi -t 10 -i anullsrc=r=44100:cl=stereo -filter_complex "[0][1]concat=n=1:v=1:a=1" output.mp4

    - name: Upload processed video
      uses: actions/upload-artifact@v2
      with:
        name: processed-video
        path: output.mp4
