
name: Apply Linear Gradient to Image

on:
  push:
    branches:
      - main

jobs:
  apply-gradient:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install FFmpeg
      run: sudo apt-get install ffmpeg

    - name: Apply Linear Gradient to Image
      run: |
        # Define input and output file paths
        INPUT_FILE="./images (31).jpeg"
        OUTPUT_FILE="./output_image.jpg"
        
        # Create a gradient image for the bottom 30% of the original image
        ffmpeg -f lavfi -t 1 -i color=black:s=1920x1080 -vf "gradient=s=1920x324:r=0:g=0:b=0:a=1[grad]" -y gradient.png
        
        # Combine the gradient with the original image, overlaying it on the bottom 30%
        ffmpeg -i "$INPUT_FILE" -i gradient.png -filter_complex "[0:v][1:v]overlay=0:H*0.7" -y "$OUTPUT_FILE"

    - name: Upload result image
      uses: actions/upload-artifact@v4
      with:
        name: output-image
        path: ./output_image.jpg
