
name: Apply Gradient Effect and Text Overlay to Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  apply_gradient:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Apply gradient effect and overlay text
        run: |
          # Define input and output file paths
          input_image="images (31).jpeg"
          output_image="output_gradient_image.jpg"
          
          # Apply the gradient effect using FFmpeg
          ffmpeg -i "$input_image" -filter_complex "[0]split[base][overlay]; \
          [overlay]geq='if(gte(Y, H/2), 255, 0)':128:128[overlay]; \
          [base][overlay]overlay=0:H/2, \
          drawtext=text='Your Text Here':fontcolor=white:fontsize=40:x=(w-text_w)/2:y=H-60" \
          "$output_image"

      - name: Upload modified image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-image
          path: output_gradient_image.jpg
