
name: Apply Vignette Effect to Image

on:
  push:
    branches:
      - main

jobs:
  apply-vignette:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install FFmpeg
      run: sudo apt-get install ffmpeg

    - name: Apply Vignette Effect to Image
      run: |
        # Define input and output file paths
        INPUT_FILE="./images (31).jpeg"
        OUTPUT_FILE="./output_image_vignette.jpg"

        # Apply gradient overlay with specific opacity stops
        ffmpeg -i "$INPUT_FILE" -vf "
          format=rgba,
          geq=r='p(X,Y)':g='p(X,Y)':b='p(X,Y)':a='
            if(gte(Y,H*0.9),255,
            if(gte(Y,H*0.8),204,
            if(gte(Y,H*0.7),0,0)))'
        " -y "$OUTPUT_FILE"

    - name: Upload result image
      uses: actions/upload-artifact@v4
      with:
        name: output-image-vignette
        path: ./output_image_vignette.jpg
