
name: Update Product File

on:
  workflow_dispatch:  # Trigger the workflow manually via GitHub Actions UI

jobs:
  update-product:
    runs-on: ubuntu-latest  # The job runs on an Ubuntu virtual machine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Check out the repository to get the code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Set up Python environment (3.x is fine)

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install any necessary Python dependencies

      - name: Read product from auto.txt and save it to product.txt
        run: |
          if [ -s auto/auto.txt ]; then  # Check if auto.txt is not empty
            FIRST_PRODUCT=$(head -n 1 auto/auto.txt)  # Read the first product from auto.txt
            echo "$FIRST_PRODUCT" > auto/product.txt  # Save it to product.txt
            sed -i '1d' auto/auto.txt  # Remove the first line from auto.txt
            echo "Selected product: $FIRST_PRODUCT"  # Log the selected product
          else
            echo "auto.txt is empty or missing." > auto/product.txt  # If auto.txt is empty, log a message
          fi

      - name: Run Fob.py and check output
        run: |
          OUTPUT=$(python Fob.py)  # Run Fob.py and capture the output
          echo "Output from Fob.py: $OUTPUT"
          if [[ "$OUTPUT" == "no" ]]; then  # Check if the output is "no"
            echo "$FIRST_PRODUCT" >> auto_no.txt  # Save the product to auto_no.txt
            # Get the next product from auto.txt and replace the previous one
            NEXT_PRODUCT=$(head -n 1 auto/auto.txt)
            echo "$NEXT_PRODUCT" > auto/product.txt
            sed -i '1d' auto/auto.txt
            echo "Replaced product with: $NEXT_PRODUCT"
          fi

      - name: Run additional Python scripts (Fob1.py to Fob6.py)
        run: |
          python Fob1.py  # Run Fob1.py
          python Fon2.py  # Run Fon2.py
          python Fon3.py  # Run Fon3.py
          python Fob4.py  # Run Fob4.py
          python Fob5.py  # Run Fob5.py
          python Fob6.py  # Run Fob6.py

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"  # Configure Git user
          git config --global user.email "actions@github.com"  # Configure Git email
          git add auto/product.txt auto/auto.txt auto_no.txt  # Add the modified files to git
          git commit -m "Updated product.txt with a new product, handled 'no' result"  # Commit the changes
          git push  # Push the changes to the repository
