
name: Run Fob Scripts Sequentially

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Fob.py
        run: python Fob.py

      - name: Run Fob1.py
        run: python Fob1.py

      - name: Run Fob2.py
        run: python Fob2.py

      - name: Run Fob3.py
        run: python Fob3.py

      - name: Run Fob4.py
        run: python Fob4.py

      - name: Run Fob5.py
        run: python Fob5.py

      - name: Run Fob6.py
        run: python Fob6.py
