
name: Run Fob Scripts and Manage auto.txt

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Process auto.txt (Remove First Line and Save)
        run: |
          mkdir -p myd  # Ensure 'myd' directory exists
          
          # Extract the first line (to be saved)
          head -n 1 auto.txt > myd/auto_used.txt
          
          # Remove the first line and save the remaining lines
          tail -n +2 auto.txt > auto_tmp.txt
          mv auto_tmp.txt auto.txt  # Replace auto.txt with updated version

          # Print contents for verification
          echo "Saved first line to myd/auto_used.txt:"
          cat myd/auto_used.txt
          
          echo "Updated auto.txt:"
          cat auto.txt

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Fob.py
        env:
          GROQ_API: ${{ secrets.GROQ_API }}
        run: |
          echo "Running Fob.py..."
          python Fob.py

      - name: Run Fob1.py
        env:
          GROQ_API: ${{ secrets.GROQ_API }}
        run: |
          echo "Running Fob1.py..."
          python Fob1.py

      - name: Run Fob2.py  # Add Fob2.py
        env:
          GROQ_API: ${{ secrets.GROQ_API }}
        run: |
          echo "Running Fob2.py..."
          python Fob2.py

      - name: Run Fob3.py
        env:
          GROQ_API: ${{ secrets.GROQ_API }}
        run: |
          echo "Running Fob3.py..."
          python Fob3.py

      - name: Run Fob4.py
        env:
          GROQ_API: ${{ secrets.GROQ_API }}
        run: |
          echo "Running Fob4.py..."
          python Fob4.py

      - name: Run Fob5.py
        env:
          GROQ_API: ${{ secrets.GROQ_API }}
        run: |
          echo "Running Fob5.py..."
          python Fob5.py

      - name: Run Fob7a.py
        env:
          GROQ_API: ${{ secrets.GROQ_API }}
        run: |
          echo "Running Fob7a.py..."
          python Fob7a.py

      - name: Commit and Push Updated Files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          
          # Pull the latest changes from the remote repository to avoid conflicts
          git pull origin main || echo "No updates from remote"
          
          git add auto.txt myd/auto_used.txt || echo "No changes to commit"
          git commit -m "Updated auto.txt and moved first line to myd/auto_used.txt" || echo "Nothing to commit"
          
          # Push changes without using GitHub token, just plain push
          git push || echo "Nothing to push"
