
name: Gemini 2.5 Flash Voiceover

on:
  workflow_dispatch:

jobs:
  generate-voiceover:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai

      - name: Run Gemini 2.5 Flash Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API }}
        run: python GEMINI.py
