
name: Apply Gradient Effect to Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  apply_gradient:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install opencv-python

      - name: Apply gradient effect to image
        run: |
          ls -alh  # Verify the image exists
          python apply_gradient.py  # Run the script

      - name: List files after processing
        run: ls -alh

      - name: Commit and push modified image
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add output_gradient_image.jpeg
          git commit -m "Added gradient image"
          git push
