
name: Apply Gradient Effect to Image using OpenCV

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  apply_gradient:
    runs-on: ubuntu-latest
    
    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies (OpenCV and NumPy)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-opencv
          pip install numpy

      # Run the Python script to apply gradient effect
      - name: Apply gradient effect to image
        run: |
          python apply_gradient.py  # updated name of the Python script

      # Upload the modified image as artifact
      - name: Upload modified image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-image
          path: output_gradient_image_opencv.png
