
name: Apply Gradient Effect to Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  apply_gradient:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install opencv-python

      - name: Apply gradient effect to image
        run: |
          # Ensure the image is available in the repo
          ls -alh
          
          # Run the Python script to apply the gradient
          python apply_gradient.py

      - name: List files to verify image creation
        run: |
          ls -alh

      - name: Upload modified image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-image
          path: output_gradient_image.jpeg
