
name: Process Image with Linear Gradient and Text

on:
  push:
    branches:
      - main

jobs:
  process-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install ImageMagick and font utilities
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick fontconfig

    - name: Setup Font
      run: |
        mkdir -p ~/.fonts
        # Fetch font from your main branch in the repository
        curl -L https://github.com/Starches71/71/raw/main/FontsFree-Net-Proxima-Nova-Bold-It.otf -o ~/.fonts/ProximaNovaBoldIt.otf
        fc-cache -fv  # Rebuild font cache

    - name: Get Image Dimensions
      id: dimensions
      run: |
        # Get the dimensions of the base image to apply gradient accordingly
        width=$(identify -format "%w" "images (31).jpeg")
        height=$(identify -format "%h" "images (31).jpeg")
        echo "width=$width" >> $GITHUB_ENV
        echo "height=$height" >> $GITHUB_ENV

    - name: Apply Linear Gradient and Add Text
      run: |
        # Apply the gradient
        convert "images (31).jpeg" -size ${width}x${height} gradient:white-black -compose Multiply -gravity center -composite gradient_image.jpeg
        
        # Add text overlay at the bottom of the image
        convert gradient_image.jpeg \
          -font ~/.fonts/ProximaNovaBoldIt.otf \
          -pointsize $((height / 15)) \  # Dynamically adjust font size based on image height
          -fill white \
          -gravity south \  # Place the text at the bottom
          -annotate +0+20 "Game over for ChatGPT and Gemini? This auto AI was launched and doesn't require human." \
          extended_image.jpeg

    - name: Upload Processed Image
      uses: actions/upload-artifact@v4
      with:
        name: extended-image
        path: extended_image.jpeg
