name: Process Image with Text

on:
  push:
    branches:
      - main

jobs:
  process_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Define text and parameters
        run: |
          text="My father is from my daughter's Franchise, he is good one there For one who hates it"
          max_width=240
          font_size=13
          font_file="/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"

          # Wrap text to fit the max width
          wrapped_text=$(echo "$text" | fold -w $max_width)

          # Calculate bottom offset (30% from the bottom)
          height=720  # You can set the height dynamically if needed
          bottom_offset=$(echo "$height * 0.30" | bc)

          # Escape the wrapped text to handle special characters properly
          wrapped_text_escaped=$(echo "$wrapped_text" | sed 's/ /\\ /g')

          # Use the wrapped text in the ffmpeg command
          echo "$wrapped_text_escaped"

      - name: Process image with ffmpeg
        run: |
          # Create an image with text using ffmpeg
          ffmpeg -f lavfi -t 5 -i color=c=black:s=640x480 -vf "drawtext=text='$wrapped_text_escaped':fontfile=$font_file:fontsize=$font_size:fontcolor=white:x=(w-text_w)/2:y=h-($bottom_offset)-((h-text_h)/3)" output_with_text.png

      - name: Upload result image
        uses: actions/upload-artifact@v4
        with:
          name: processed-image
          path: output_with_text.png
