
name: Generate Image from HTML and CSS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 1: Install Node.js and Puppeteer
    - name: Set up Node.js for Puppeteer
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Puppeteer
      run: |
        npm init -y
        npm install puppeteer

    # Step 2: Copy your image to the right place (assuming it's in a directory)
    - name: Ensure Image Exists
      run: |
        if [ ! -f "images/your_image.jpeg" ]; then
          echo "Image not found!"
          exit 1
        fi
        echo "Image found."

    # Step 3: Run Puppeteer to generate the image with gradient and text overlay
    - name: Run Puppeteer to generate the image
      run: |
        node generate_image.js

    # Step 4: Verify that the image was created
    - name: Verify the generated image
      run: |
        if [ ! -f "output_image.png" ]; then
          echo "output_image.png not created!"
          exit 1
        else
          echo "output_image.png created successfully!"
        fi

    # Step 5: Upload the generated image as an artifact
    - name: Upload the generated image as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: generated-image
        path: output_image.png
