
name: ImageMagick Overlay

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  image-overlay:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up ImageMagick
      run: |
        sudo apt update
        sudo apt install -y imagemagick

    - name: Verify ImageMagick Installation
      run: convert -version

    - name: Download Image from Repository
      run: cp "images (31).jpeg" base_image.jpeg  # Handle files with spaces

    - name: Get Dimensions of Base Image
      run: |
        # Get the dimensions (width and height) of the base image
        dimensions=$(identify -format "%wx%h" base_image.jpeg)
        width=$(echo $dimensions | cut -d'x' -f1)
        height=$(echo $dimensions | cut -d'x' -f2)
        echo "Base Image Dimensions: $width x $height"

    - name: Create Gradient with Same Dimensions
      run: |
        # Create a gradient image with the same dimensions as the base image
        convert -size ${width}x${height} gradient:white-black gradient.png
        ls -l gradient.png  # Debugging step to check if the gradient file is created

    - name: Apply Gradient Overlay with Layering
      run: |
        # Check if gradient image exists
        if [ ! -f gradient.png ]; then
          echo "Error: gradient.png not found!"
          exit 1
        fi

        # Apply gradient overlay on the base image
        convert "base_image.jpeg" \
          gradient.png -resize ${width}x${height} \
          -compose overlay -gravity center -composite \
          output.png

    - name: Upload Processed Image
      uses: actions/upload-artifact@v4
      with:
        name: overlayed-image
        path: output.png
