
name: Image Processing Pipeline

on:
  push:
    branches:
      - main

jobs:
  process_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Fonts
        run: |
          mkdir -p ~/.fonts
          curl -L https://github.com/Starches71/71/raw/main/FontsFree-Net-Proxima-Nova-Bold-It.otf%20(1).ttf -o ~/.fonts/FontsFree-Net-Proxima-Nova-Bold-It.otf1.ttf
          fc-cache -fv

      - name: Fetch Image Dimensions
        run: |
          # Fetch image dimensions to dynamically adjust font size
          width=$(identify -format "%w" gradient_image.jpeg)
          height=$(identify -format "%h" gradient_image.jpeg)
          echo "Width: $width, Height: $height"

      - name: Apply Gradient to Image
        run: |
          # Apply a gradient to the image
          convert gradient_image.jpeg \
            -size ${width}x${height} gradient:blue-yellow \
            -gravity center \
            -composite gradient_image_with_gradient.jpeg

      - name: Add White Text at Bottom
        run: |
          # Add simple white text to the gradient image at the bottom
          convert gradient_image_with_gradient.jpeg \
            -font ~/.fonts/FontsFree-Net-Proxima-Nova-Bold-It.otf\ 1.ttf \
            -pointsize $((height / 15)) \  # Dynamically adjust font size based on image height
            -fill white \
            -gravity south \  # Place the text at the bottom
            -annotate +0+20 "Sample Text" \  # Simple placeholder text
            extended_image.jpeg

      - name: Upload Processed Image
        uses: actions/upload-artifact@v2
        with:
          name: processed-image
          path: extended_image.jpeg
