- name: Get image dimensions
      run: |
        width=$(identify -format "%w" base_image.jpeg)
        height=$(identify -format "%h" base_image.jpeg)
        new_height=$((height + 20))  # Adjust height slightly
        echo "WIDTH=$width" >> $GITHUB_ENV
        echo "HEIGHT=$height" >> $GITHUB_ENV
        echo "NEW_HEIGHT=$new_height" >> $GITHUB_ENV

    - name: Extend Image with White Bottom
      run: |
        convert base_image.jpeg -background white -gravity north -extent ${WIDTH}x${NEW_HEIGHT} extended_image.jpeg

    - name: Apply Linear Gradient Effect
      run: |
        convert extended_image.jpeg \
          -size ${WIDTH}x${NEW_HEIGHT} gradient:black-white \
          -compose Multiply -composite output.png
