- name: Add Text to Image using ffmpeg
      run: |
        text="Samsung phones can now flip into two because they are the best"
        font_size=13
        font="/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"

        # Get image width
        image_width=${{ steps.dimensions.outputs.width }}

        # Use fold to wrap text at image width
        wrapped_text=$(echo "$text" | fold -s -w $image_width)

        # Print the wrapped text (for debugging)
        echo "Wrapped text:\n$wrapped_text"

        # Use ffmpeg to add the text to the image
        ffmpeg -i output.png -vf "drawtext=text='$wrapped_text':fontfile=$font:fontsize=$font_size:fontcolor=white:x=(w-text_w)/2:y=h-text_h-10" -y output_with_text.png
