
name: Tor YouTube Download

on: [push]

jobs:
  download_video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies (Tor, yt-dlp, dig)
        run: |
          sudo apt update
          sudo apt install -y tor yt-dlp dnsutils jq
          echo "SocksPort 9050" | sudo tee -a /etc/tor/torrc
          echo "DNSPort 53" | sudo tee -a /etc/tor/torrc
          echo "AutomapHostsOnResolve 1" | sudo tee -a /etc/tor/torrc
          sudo systemctl restart tor
          sleep 10  # Wait for Tor to start

      - name: Verify Tor IP
        run: |
          echo "Checking Tor exit node IP..."
          torsocks curl -s https://check.torproject.org/api/ip | jq .

      - name: Verify DNS Resolution via Tor
        run: |
          echo "Checking DNS resolution via Tor..."
          torsocks dig +short youtube.com || echo "DNS resolution failed"

      - name: Download YouTube Video via Tor
        run: |
          torsocks -i yt-dlp -o "video.mp4" "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

      - name: Remove Video After Download
        run: rm -f video.mp4
