name: Tor YouTube Download

on: [push]

jobs:
  download_video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies (Tor, Privoxy, yt-dlp)
        run: |
          sudo apt update
          sudo apt install -y tor privoxy yt-dlp curl jq

          echo "forward-socks5t / 127.0.0.1:9050 ." | sudo tee /etc/privoxy/config
          sudo systemctl restart privoxy

          echo "SocksPort 9050" | sudo tee -a /etc/tor/torrc
          echo "DNSPort 53" | sudo tee -a /etc/tor/torrc
          echo "AutomapHostsOnResolve 1" | sudo tee -a /etc/tor/torrc
          sudo systemctl restart tor
          sleep 10

      - name: Verify Tor IP
        run: |
          echo "Checking Tor exit node IP..."
          curl -sx http://127.0.0.1:8118 https://check.torproject.org/api/ip | jq .

      - name: Verify DNS Resolution (Workaround)
        run: |
          echo "Resolving youtube.com via Tor..."
          curl -sx http://127.0.0.1:8118 https://dns.google/resolve?name=youtube.com | jq .

      - name: Download YouTube Video via Tor
        run: |
          export http_proxy="http://127.0.0.1:8118"
          export https_proxy="http://127.0.0.1:8118"
          torsocks yt-dlp -o "video.mp4" "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

      - name: Remove Video After Download
        run: rm -f video.mp4
