
name: Fetch Top 3 Hotel Links in Jeddah

on:
  workflow_dispatch:

jobs:
  search_hotels:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Tor
      run: |
        sudo apt-get update
        sudo apt-get install tor
        sudo service tor start

    - name: Update necessary packages
      run: |
        sudo apt-get install curl jq

    - name: Check Tor exit node IP
      run: |
        echo "Checking Tor exit node IP..."
        curl --socks5 127.0.0.1:9050 https://check.torproject.org/api/ip

    - name: Resolve google.com via Tor
      run: |
        echo "Resolving google.com via Tor..."
        curl --socks5 127.0.0.1:9050 https://dns.google.com/resolve?name=www.google.com&type=A

    - name: Search for top hotels in Jeddah
      run: |
        SEARCH_TERM="best hotels in Jeddah"
        QUERY="https://www.google.com/search?q=${SEARCH_TERM}"
        echo "Fetching top hotels in Jeddah..."

        # Using curl to search and parse links from the results
        SEARCH_RESULTS=$(curl -s --socks5 127.0.0.1:9050 "${QUERY}")
        TOP_3_LINKS=$(echo "${SEARCH_RESULTS}" | grep -oP 'https://[^\s"]+' | head -n 3)

        echo "Top 3 hotel links in Jeddah:"
        echo "${TOP_3_LINKS}"

        # Saving links to a file
        echo "${TOP_3_LINKS}" > top_hotels_jeddah.txt

    - name: Display saved links
      run: |
        cat top_hotels_jeddah.txt
