
name: Download YouTube Video via Tor

on: 
  workflow_dispatch  # Manually trigger the workflow

jobs:
  download_video:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Tor
      run: |
        sudo apt update
        sudo apt install -y tor torsocks
        sudo systemctl start tor
        sleep 10  # Wait for Tor to establish a connection

    - name: Verify Tor IP
      run: |
        torsocks curl --silent https://ifconfig.me
        echo "Tor connection established."

    - name: Install yt-dlp
      run: |
        sudo apt install -y yt-dlp  # Install latest yt-dlp
        yt-dlp --version  # Verify installation

    - name: Download YouTube Video via Tor
      run: |
        torsocks yt-dlp -o "video.mp4" "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

    - name: Upload Video as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: downloaded-video
        path: video.mp4
