
name: Fetch IP Address

on:
  workflow_dispatch:

jobs:
  get-ip:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Public IP
        run: |
          IP=$(curl -s ifconfig.me)
          echo "Public IP: $IP"
