
name: Tor YouTube Download with Leak Protection

on: [push]

jobs:
  download_video:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Tor, yt-dlp, and dependencies
        run: |
          sudo apt update
          sudo apt install -y tor yt-dlp jq dnsutils
          echo "SocksPort 9050" | sudo tee -a /etc/tor/torrc
          echo "DNSPort 9053" | sudo tee -a /etc/tor/torrc  # Force DNS resolution via Tor
          echo "AutomapHostsOnResolve 1" | sudo tee -a /etc/tor/torrc
          sudo systemctl start tor
          sleep 10  # Wait for Tor to fully initialize
      
      - name: Verify Tor IP (Checking for leaks)
        run: |
          echo "Checking Tor exit node IP..."
          torsocks curl -s https://check.torproject.org/api/ip | jq .
          echo "Checking DNS resolution via Tor..."
          torsocks nslookup youtube.com
      
      - name: Download YouTube Video via Tor
        run: |
          torsocks yt-dlp -o "video.mp4" "https://www.youtube.com/watch?v=dQw4w9WgXcQ"  # Replace with a valid video ID
          
      - name: Cleanup downloaded video
        run: |
          rm -f video.mp4  # Deletes the video after download
