name: Download YouTube Video via Tor

on:
  push:
    branches:
      - main

jobs:
  download_video:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update system packages
      run: sudo apt-get update

    - name: Install dependencies
      run: |
        sudo apt-get install -y tor torsocks libevent-2.1-7t64
        python3 -m pip install --upgrade yt-dlp

    - name: Start Tor service
      run: sudo systemctl start tor

    - name: Check Tor IP
      run: |
        curl -s https://check.torproject.org/api/ip | jq

    - name: Resolve YouTube via Tor
      run: |
        curl -s https://www.youtube.com --resolve youtube.com:443:127.0.0.1

    - name: Set proxy for yt-dlp
      run: export http_proxy="http://127.0.0.1:8118"

    - name: Download video
      run: |
        yt-dlp https://www.youtube.com/watch?v=dQw4w9WgXcQ

    - name: Check if download succeeded
      run: echo "Video download finished!"
