
name: WireGuard VPN on GitHub Actions
on: [push]

jobs:
  vpn-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up WireGuard VPN
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard

          # Generate private and public keys
          wg genkey | tee privatekey | wg pubkey > publickey
          
          # Display the keys (you'll need these later)
          cat privatekey
          cat publickey

          # Create WireGuard config file
          echo "[Interface]" | sudo tee /etc/wireguard/wg0.conf
          echo "PrivateKey = $(cat privatekey)" | sudo tee -a /etc/wireguard/wg0.conf
          echo "ListenPort = 51820" | sudo tee -a /etc/wireguard/wg0.conf
          echo "Address = 10.0.0.1/24" | sudo tee -a /etc/wireguard/wg0.conf
          echo "" | sudo tee -a /etc/wireguard/wg0.conf

          # Start WireGuard
          sudo systemctl start wg-quick@wg0
          sudo systemctl enable wg-quick@wg0

      - name: Display GitHub Actions public IP
        run: |
          curl ifconfig.me
