
name: Tor YouTube Download

on: [push]

jobs:
  download_video:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Tor and yt-dlp
        run: |
          sudo apt update
          sudo apt install -y tor yt-dlp
          echo "SocksPort 9050" | sudo tee -a /etc/tor/torrc
          sudo systemctl start tor
          sleep 10  # Wait for Tor to start
      
      - name: Verify Tor connection
        run: |
          torsocks curl -s https://check.torproject.org/api/ip | jq .
      
      - name: Download YouTube Video via Tor
        run: |
          torsocks yt-dlp -o "video.mp4" "https://www.youtube.com/watch?v=VIDEO_ID"
      
      - name: Upload video artifact
        uses: actions/upload-artifact@v4
        with:
          name: downloaded_video
          path: video.mp4
