
name: Download and Upload Video via Tor

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  workflow_dispatch:  # Allow manual trigger from the GitHub Actions UI

jobs:
  run:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the version of Python to use

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tor torsocks  # Install Tor and torsocks
          pip install yt-dlp google-api-python-client google-auth-oauthlib google-auth-httplib2  # Install Python dependencies

      - name: Run kabaju2.py script
        run: python3 kabaju2.py  # Run your Python script
