
name: Download YouTube Video

on:
  push:
    branches:
      - main

jobs:
  download_video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Download YouTube video
      run: |
        python download_video.py
