name: Auto Video Upload

on:
  push:
    branches:
      - main  # Runs this action on push to the 'main' branch
  workflow_dispatch:  # Allows for manual trigger

jobs:
  upload_video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from GitHub
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use Python 3.x

    - name: Install yt-dlp
      run: |
        python -m pip install --upgrade pip
        pip install yt-dlp

    - name: Install Requests
      run: pip install requests

    - name: Run Python script to download and upload video
      run: python autopost_video.py
