name: Manim Gradient Filter and Text Overlay

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-image:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Python and dependencies
    - name: Set up Python and dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-dev build-essential
        pip3 install --upgrade pip
        pip3 install manim

    # Step 3: Verify Manim installation
    - name: Verify Manim installation
      run: |
        manim --version

    # Step 4: Download Image from Repository (ensure file exists)
    - name: Download Image from Repository
      run: |
        cp "images (31).jpeg" base_image.jpeg || (echo "Image not found" && exit 1)

    # Step 5: Verify that input image exists
    - name: Verify that input image exists
      run: |
        if [ ! -f "base_image.jpeg" ]; then
          echo "base_image.jpeg not found!"
          exit 1
        else
          echo "base_image.jpeg found!"
        fi

    # Step 6: Generate Image with Manim
    - name: Generate Image with Manim
      run: |
        python3 generate_image.py

    # Step 7: Verify that generated image exists
    - name: Verify that generated image exists
      run: |
        if [ ! -f "media/images/GradientTextScene/1080p60/scene_1.png" ]; then
          echo "Generated image not found!"
          exit 1
        else
          echo "Generated image found!"
        fi

    # Step 8: List files in current directory after processing
    - name: List files in current directory after processing
      run: ls -l

    # Step 9: Upload Processed Image as Artifact
    - name: Upload Processed Image as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: image-artifact
        path: media/images/GradientTextScene/1080p60/scene_1.png
