name: Image Manipulation with Pillow

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch

jobs:
  image-manipulation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Using v4 to checkout code

    - name: Set up Python environment
      uses: actions/setup-python@v4  # Using v4 to set up Python environment
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow

    - name: Run the image manipulation Python script
      run: |
        python image_overlay.py

    - name: Upload the result image
      uses: actions/upload-artifact@v4  # Using v4 to upload the artifact
      with:
        name: manipulated-image
        path: img_result.png
