
name: Run Skia Image Processing

on: push

jobs:
  run-skia:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify input image exists
        run: |
          if [ ! -f "base_image.jpeg" ]; then
            echo "Error: base_image.jpeg not found!"
            exit 1
          fi

      - name: Install dependencies
        run: |
          pip install skia-python

      - name: Run Python script
        run: python3 skia_edit.py

      - name: Verify Output Image
        run: |
          if [ ! -f "output_with_text.png" ]; then
            echo "Error: Output image not generated!"
            exit 1
          fi

      - name: Upload Processed Image as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: processed-image
          path: output_with_text.png
