
name: Skia Image Processing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  image-processing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip
        pip install pillow skia-python

    - name: Verify Python Libraries
      run: |
        python3 -c "import PIL, skia; print('Pillow and Skia installed successfully!')"

    - name: Run Skia Script
      run: python3 skia_edit.py

    - name: Verify Output Image
      run: |
        if [ ! -f "output_with_text.png" ]; then
          echo "Error: output_with_text.png was not created!"
          exit 1
        else
          echo "Success: output_with_text.png was created!"
        fi

    - name: Upload Processed Image as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: skia-image
        path: output_with_text.png
