name: Image Processing with Skia

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  image-processing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install skia-python

    - name: Verify Skia Installation
      run: |
        python -c "import skia; print(skia.__version__)"

    - name: List files in current directory (debugging)
      run: ls -l

    - name: Download Image from Repository
      run: |
        mkdir -p images
        curl -L -o images/"images (31).jpeg" https://github.com/Starches71/71/raw/main/images%20(31).jpeg

    - name: Verify that input image exists (debugging)
      run: |
        if [ ! -f "images/images (31).jpeg" ]; then
          echo "Input image not found!"
          exit 1
        else
          echo "Input image found!"
        fi

    - name: Run Skia Image Processing Script
      run: |
        python skia_edit.py

    - name: Verify that output image was created (debugging)
      run: |
        if [ ! -f "output_image.jpeg" ]; then
          echo "Output image not created!"
          exit 1
        else
          echo "Output image created successfully!"
        fi

    - name: Upload Processed Image as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: processed-image
        path: output_image.jpeg
