
name: Search Creative Commons YouTube Videos via Tor

on:
  push:
    branches:
      - main  # Trigger when pushing to the main branch

jobs:
  search_video:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Tor
        run: |
          sudo apt-get update
          sudo apt-get install tor
          sudo service tor start

      - name: Update yt-dlp
        run: |
          python3 -m pip install --upgrade yt-dlp

      - name: Check Tor exit node IP
        run: |
          echo "Checking Tor exit node IP..."
          curl --socks5 127.0.0.1:9050 https://check.torproject.org/api/ip

      - name: Resolve youtube.com via Tor
        run: |
          echo "Resolving youtube.com via Tor..."
          curl --socks5 127.0.0.1:9050 "https://dns.google.com/resolve?name=www.youtube.com&type=A"

      - name: Search YouTube for "smartphone" (Creative Commons, sorted by views)
        run: |
          echo "Searching for Creative Commons videos about 'smartphone'..."
          yt-dlp \
            --proxy "socks5://127.0.0.1:9050" \
            "ytsearch50:smartphone cc" \
            --match-filter "license=Creative Commons" \
            --print "%(view_count)s|%(title)s|%(webpage_url)s" > raw_results.txt

          echo "Sorting results by view count..."
          sort -t '|' -k1,1nr raw_results.txt > search_results.txt

          echo "Top Creative Commons YouTube videos:"
          cat search_results.txt
