
name: Test Speech-to-Speech Translation

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test-translation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install required dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg curl

      - name: Download Hindi audio file
        run: |
          mkdir -p test_audio
          curl -L -o test_audio/hindi.wav "https://www.voiptroubleshooter.com/open_speech/india/OSR_in_000_0071_16k.wav"

      - name: Install SeamlessM4T and soundfile
        run: |
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install git+https://github.com/facebookresearch/seamless_communication
          pip install soundfile

      - name: Translate Hindi speech to English speech
        run: |
          python3 <<EOF
          from seamless_communication.models.inference import Translator
          import torchaudio
          import os

          translator = Translator()
          input_path = "test_audio/hindi.wav"
          output_path = "test_audio/output.wav"

          # Perform speech-to-speech translation from Hindi to English
          output = translator.predict(
              input=input_path,
              task_str="S2ST",
              tgt_lang="eng"
          )

          # Save output waveform
          torchaudio.save(output_path, output.audio_wav.unsqueeze(0), sample_rate=output.sample_rate)
          EOF

      - name: Upload translated audio artifact
        uses: actions/upload-artifact@v4
        with:
          name: translated_speech
          path: test_audio/output.wav
