name: Demucs Music Detection

on:
  workflow_dispatch:

jobs:
  detect_music:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Demucs
      run: |
        pip install -U demucs torch torchaudio

    - name: Download random small audio sample
      run: |
        mkdir -p input
        curl -L -o input/sample.wav https://github.com/deezer/spleeter/raw/master/audio_example.mp3

    - name: Run Demucs (extract vocals & instruments)
      run: |
        demucs --two-stems=vocals input/sample.wav

    - name: Check for music presence
      run: |
        python3 <<EOF
        import os
        import wave
        import contextlib

        path = "separated/htdemucs/sample/no_vocals.wav"
        if not os.path.exists(path):
            print("No vocals stem not found!")
            exit(1)

        with contextlib.closing(wave.open(path, 'r')) as f:
            frames = f.getnframes()
            rate = f.getframerate()
            duration = frames / float(rate)
            print(f"Instrumental Duration: {duration:.2f} seconds")

            if duration > 1:
                print(">> Music detected in audio!")
            else:
                print(">> No music detected.")
        EOF

    - name: Upload Stems as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: demucs_output
        path: separated/
