
name: Run starches.py and related scripts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Set Up Required Directories
      run: |
        mkdir -p best best_20 best_audio best_clean best_clip best_clip2 best_clip3 best_descriptions best_dir best_final best_final2 best_intro best_io best_io2 best_io3 best_join best_join_vid best_link best_outro best_vid best_vid_clean places
        echo "Directories created successfully!"

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl ffmpeg
        echo "System dependencies installed successfully!"

    - name: Install Python Dependencies
      run: |
        pip install -r requirements.txt
        pip install flask  # Add Flask installation
        echo "Python dependencies installed successfully!"

    - name: Run starches.py
      run: python3 starches.py  # Run starches.py

    - name: Run htl1.py
      run: python3 htl1.py  # Run htl1.py

    - name: Run htl2.py
      run: python3 htl2.py  # Run htl2.py

    - name: Run htl3.py
      run: python3 htl3.py  # Run htl3.py

    - name: Run htl4.py
      run: python3 htl4.py  # Run htl4.py

    - name: Run htl5.py
      run: python3 htl5.py  # Run htl5.py

    - name: Run htl6.py
      run: python3 htl6.py  # Run htl6.py

    - name: Start YouTube Downloader API
      run: |
        echo "Starting YouTube Downloader API..."
        nohup python3 main.py &  # Runs API in the background
        sleep 10  # Wait 10 seconds to ensure API starts
        echo "API started successfully!"

    - name: Run htl7.py Using the API
      run: python3 htl7.py  # Uses API instead of yt-dlp

    - name: Run htl8.py
      run: python3 htl8.py

    - name: Run htl9.py
      run: python3 htl9.py

    - name: Run htl10.py
      run: python3 htl10.py

    - name: Run htl10a.py
      run: python3 htl10a.py

    - name: Run htl10aa.py
      run: python3 htl10aa.py

    - name: Run htl10b.py
      run: python3 htl10b.py

    - name: Run htl11.py
      run: python3 htl11.py

    - name: Run htl11a.py
      run: python3 htl11a.py

    - name: Run htl11b.py
      run: python3 htl11b.py

    - name: Run htl12.py
      run: python3 htl12.py
