name: Run Starches Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-starches:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # Specify a valid Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install groq  # Install the Groq client library

      # Step 4: Run the starches.py script
      - name: Run starches.py
        run: python starches.py

      # Step 5: List output files (optional for debugging)
      - name: List output files
        run: ls -R
