
name: Generate Thumbnail

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-thumbnail:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install System-Level Dependencies
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev libcairo2-dev libpango1.0-dev ffmpeg pkg-config

      # Step 3: Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 4: Install Python Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install manim icrawler importlib-metadata

      # Step 5: Verify Installation
      - name: Verify Manim Installation
        run: |
          python -c "import manim; print('Manim is installed and working')"

      # Step 6: Run Python Script
      - name: Run Script
        run: |
          python generate_thumbnail.py
