name: Generate Thumbnails

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install icrawler

    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Run Thumbnail Script
      run: python generate_thumbnail_ffmpeg.py

    - name: Upload Generated Thumbnails
      uses: actions/upload-artifact@v3
      with:
        name: thumbnails
        path: thumbnail_with_lines.jpg
