
name: Generate Thumbnail

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-thumbnail:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install System-Level Dependencies
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev libcairo2-dev libpango1.0-dev ffmpeg pkg-config

      # Step 3: Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 4: Install Python Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install remotion icrawler importlib-metadata

      # Step 5: Verify Remotion Installation
      - name: Verify Remotion Installation
        run: |
          python -c "import remotion; print('Remotion is installed and working')"

      # Step 6: Download Images (using icrawler)
      - name: Download Images
        run: |
          python -c 'from icrawler.builtin import GoogleImageCrawler; crawler = GoogleImageCrawler(storage={"root_dir": "downloaded_images"}); crawler.crawl(keyword="San Francisco", max_num=10)'

      # Step 7: Run Python Script to Generate Thumbnail
      - name: Run Script
        run: |
          python generate_thumbnail.py

      # Step 8: Upload Generated Thumbnail
      - name: Upload Generated File
        uses: actions/upload-artifact@v3
        with:
          name: generated-thumbnail
          path: output/thumbnail_with_text.mp4
