
name: Generate Thumbnail

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-thumbnail:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install icrawler

    - name: Run script to download image and generate thumbnail
      run: python generate_thumbnail_ffmpeg.py

    - name: Debug: List files in the working directory
      run: ls -al

    - name: Upload generated thumbnail as artifact
      uses: actions/upload-artifact@v3
      with:
        name: generated-thumbnail
        path: thumbnail_with_text_vignette.jpg
