
name: Generate Thumbnail with FFmpeg

on:
  push:
    branches:
      - main

jobs:
  generate-thumbnail:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Check out repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install icrawler

    # Step 4: Install FFmpeg
    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    # Step 5: Run the script
    - name: Run generate_thumbnail script
      run: python generate_thumbnail_ffmpeg.py

    # Step 6: Upload the result as an artifact
    - name: Upload thumbnail
      uses: actions/upload-artifact@v3
      with:
        name: thumbnail
        path: thumbnail_with_text.jpg
