
name: Generate Thumbnail

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-thumbnail:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # You can use any supported Node.js version

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          npm install

      # Step 4: Install ImageMagick (for image manipulation if needed by Remotion)
      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      # Step 5: Download images (using icrawler or your method of choice)
      - name: Download Images
        run: |
          python -c 'from icrawler.builtin import GoogleImageCrawler; crawler = GoogleImageCrawler(storage={"root_dir": "downloaded_images"}); crawler.crawl(keyword="San Francisco", max_num=1)'

      # Step 6: Run the Node.js Remotion script to generate the thumbnail
      - name: Run Remotion Script
        run: |
          node generate-thumbnail.js

      # Step 7: Upload the generated thumbnail
      - name: Upload Generated Thumbnail
        uses: actions/upload-artifact@v3
        with:
          name: generated-thumbnail
          path: output/thumbnail_with_text.png
