
name: Generate Thumbnail with Text Overlay

on:
  push:
    branches:
      - main

jobs:
  generate-thumbnail:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install ImageMagick
      run: sudo apt-get install -y imagemagick

    - name: Install specific versions of MoviePy and Pillow
      run: |
        pip install moviepy==1.0.3
        pip install Pillow==9.5.0
        pip install icrawler

    - name: Run thumbnail generator
      run: python generate_thumbnail.py

    - name: Upload thumbnail to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: thumbnail
        path: output/thumbnail_with_text.png
