
name: Generate Thumbnail

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-thumbnail:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow icrawler

    # Step 4: Run the Python script
    - name: Run Thumbnail Script
      run: |
        python pillow.py

    # Step 5: Upload the output image as artifact
    - name: Upload Thumbnail
      uses: actions/upload-artifact@v3
      with:
        name: combined-thumbnail
        path: combined_image.jpg
