name: Download and Process Image

on:
  push:
    branches:
      - main

jobs:
  image_processing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install icrawler
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Download and process image
        run: |
          python3 script.py  # Replace with your Python script filename
