
name: Generate Thumbnail

on:
  push:
    branches:
      - main  # Triggers on push to 'main' branch
  workflow_dispatch:  # Allows manual trigger from the Actions tab

jobs:
  generate-thumbnail:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checks out your code from the repository

    - name: Set up Python
      uses: actions/setup-python@v2  # Sets up Python for the workflow
      with:
        python-version: '3.x'  # Specifies Python version (3.x should be fine)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install icrawler  # Installs the icrawler module (for downloading images)
        pip install ffmpeg-python  # Installs FFmpeg for Python bindings

    - name: Run the thumbnail generation script
      run: |
        python generate_thumbnail_ffmpag.py  # Runs your Python script

    - name: Upload generated thumbnail as artifact
      uses: actions/upload-artifact@v2  # Uploads the generated file as an artifact
      with:
        name: generated-thumbnail  # Name of the artifact
        path: thumbnail_with_text_vignette.jpg  # Path to the generated file (adjust if needed)
