
name: Generate Thumbnail

on:
  push:
    branches:
      - main  # Adjust this if your main branch has a different name
  workflow_dispatch:  # Optional, allows manual trigger

jobs:
  generate-thumbnail:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install icrawler

    - name: Download image from Google
      run: |
        python download_image.py  # Assuming you have a download_image.py script

    - name: Generate Thumbnail
      run: |
        python generate_thumbnail_ffmpeg.py  # Your main script to generate the thumbnail

    - name: Upload generated thumbnail as artifact
      uses: actions/upload-artifact@v3  # Updated version v3
      with:
        name: generated-thumbnail  # Name of the artifact
        path: thumbnail_with_text_vignette.jpg  # Path to the generated file
