
name: Generate Thumbnail

on:
  push:
    branches:
      - main  # This will trigger the workflow on push to the 'main' branch

jobs:
  generate-thumbnail:
    runs-on: ubuntu-latest  # The job will run on the latest Ubuntu environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # This checks out the repository so that the workflow can access your files

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Set the version of Python to use (you can adjust this if needed)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install icrawler  # Install the necessary Python dependencies (icrawler is used in your script)

    - name: Run thumbnail generation script
      run: |
        python generate_thumbnail_ffmpag.py  # This runs the Python script you want to execute

    - name: Upload generated thumbnail as artifact
      uses: actions/upload-artifact@v2  # Upload the generated file as an artifact
      with:
        name: generated-thumbnail  # The name of the artifact
        path: thumbnail_with_text_vignette.jpg  # Path to the generated file (adjust as needed)
