
name: Transcribe Uploaded WAV Audio

on:
  workflow_dispatch:

jobs:
  transcribe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python, FFmpeg, and Whisper
        run: |
          sudo apt update
          sudo apt install ffmpeg -y
          pip install git+https://github.com/openai/whisper

      - name: Check if audio file exists
        run: |
          if [ -f "Untitled notebook.wav" ]; then
            echo "Audio file found: Untitled notebook.wav"
          else
            echo "Audio file NOT found!" >&2
            exit 1
          fi

      - name: Print audio duration
        run: |
          DURATION=$(ffprobe -i "Untitled notebook.wav" -show_entries format=duration -v quiet -of csv="p=0")
          echo "Audio duration: ${DURATION} seconds"

      - name: Transcribe audio with Whisper (base, auto-detect language)
        run: |
          whisper "Untitled notebook.wav" --model base --output_format txt --output_dir .

      - name: Show transcription result
        run: |
          echo "Transcription result:"
          cat "Untitled notebook.txt"
