name: YouTube Search and Download with YouTubeExplode

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download_video:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0'

    - name: Restore .NET dependencies
      run: |
        dotnet restore

    - name: Build C# program (YouTubeSearchDownload)
      run: |
        dotnet build src/YouTubeSearchDownload/YouTubeSearchDownload.csproj

    - name: Run C# program to search and download video
      run: |
        mkdir -p best_vid
        dotnet run --project src/YouTubeSearchDownload/YouTubeSearchDownload.csproj "Sherstin hotels Jeddah" "best_vid/video.mp4"

    - name: Check if video was downloaded
      run: |
        ls -l best_vid/
