name: Build and Run YouTubeSearchDownload

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository's code

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'  # Use the .NET version your project is using

    - name: Restore .NET dependencies
      run: |
        dotnet restore YouTubeSearchDownload.csproj  # Restore dependencies from the .csproj file in the root directory

    - name: Build the project
      run: |
        dotnet build YouTubeSearchDownload.csproj  # Build the project using the .csproj file in the root directory

    - name: Run the program
      run: |
        dotnet run --project YouTubeSearchDownload.csproj "Sherstin hotels Jeddah" "best_vid/video.mp4"  # Run with the search term and output path
