
name: Download YouTube Videos with Docker

on: 
  workflow_dispatch:  # Allows manual triggering

jobs:
  download_videos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t yt-dlp-container .

      - name: Run yt-dlp in Docker
        run: |
          docker run --rm -v "$(pwd):/app" yt-dlp-container

      - name: Upload downloaded videos
        uses: actions/upload-artifact@v4
        with:
          name: samsung_s25_videos
          path: samsung_s25_*.mp4
