name: Test yt-dlp with SOCKS5 Proxy

on:
  workflow_dispatch:

jobs:
  test_yt_dlp:
    runs-on: ubuntu-latest

    steps:
      - name: Install yt-dlp
        run: sudo apt update && sudo apt install -y yt-dlp

      - name: Test yt-dlp with Proxy
        run: |
          # Set the proxy using your Android device's IP
          PROXY="socks5h://196.249.106.199:1080"

          # Download a single test video
          yt-dlp --proxy $PROXY https://www.youtube.com/watch?v=dQw4w9WgXcQ

          echo "Download test completed."
