
name: Download YouTube Videos

on: 
  push:
  workflow_dispatch:

jobs:
  download_videos:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install yt-dlp
        run: |
          sudo apt update
          sudo apt install -y yt-dlp

      - name: Download videos without saving
        run: |
          yt-dlp "ytsearch3:best hotels in Jeddah" \
          --proxy "http://41.77.7.234:3129" \
          --format best \
          --exec "echo Downloaded: {} && rm {}"
