
name: Download Best Hotels in Jeddah Videos

on:
  workflow_dispatch:

jobs:
  download_videos:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install yt-dlp
        run: sudo apt update && sudo apt install -y yt-dlp

      - name: Download first 3 videos using yt-dlp through SOCKS5 proxy
        run: |
          # Set the proxy using the IP of your Android device
          PROXY="socks5h://196.249.106.199:1080"
          
          # Search for "best hotels in Jeddah" and download the first 3 videos
          yt-dlp --proxy $PROXY "ytsearch:best hotels in Jeddah" --max-results 3
          
          # Confirm that the videos were downloaded
          echo "Download complete: First 3 videos have been downloaded."
