
name: Download YouTube Video via Tor

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  download-video:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y tor yt-dlp curl netcat-openbsd  # Fixed package name for netcat

      - name: Configure Tor for IP Change
        run: |
          echo "ControlPort 9051" | sudo tee -a /etc/tor/torrc
          echo "HashedControlPassword $(tor --hash-password 'mypassword')" | sudo tee -a /etc/tor/torrc
          sudo service tor restart
          sleep 10  # Give Tor time to reconnect

      - name: Change IP Seven Times
        run: |
          for i in {1..7}; do
              echo "Changing IP #$i..."
              echo -e 'authenticate "mypassword"\nsignal newnym\nquit' | nc localhost 9051
              sleep 10  # Wait for Tor to establish a new circuit
              new_ip=$(curl -s --socks5-hostname 127.0.0.1:9050 https://check.torproject.org/api/ip || echo "Failed to get IP")
              echo "New IP: $new_ip"
          done

      - name: Download via SOCKS5 Proxy
        run: |
          while true; do
              # Get current IP address via Tor
              ip=$(curl -s --socks5-hostname 127.0.0.1:9050 https://check.torproject.org/api/ip || echo "Failed to get IP")
              echo "Trying with IP: $ip"

              # Download video using SOCKS5 proxy
              yt-dlp --proxy "socks5h://127.0.0.1:9050" "ytsearch:sheraton hotel jeddah" --max-downloads 1

              # Check if download was successful
              if [ $? -eq 0 ]; then
                  echo "✅ Success with IP: $ip"
                  break
              else
                  echo "❌ Blocked with IP: $ip, retrying..."
                  sleep 10
              fi
          done
