
name: YouTube Download via Tor (Tanzania Exit)

on:
  workflow_dispatch  # Manual trigger

jobs:
  download-video:
    runs-on: ubuntu-latest

    steps:
      - name: Set up environment
        run: |
          sudo apt update
          sudo apt install -y tor torsocks yt-dlp curl
          
          # Configure Tor to use only Tanzania (TZ) exit nodes
          echo "ExitNodes {TZ}" | sudo tee -a /etc/tor/torrc
          echo "StrictNodes 1" | sudo tee -a /etc/tor/torrc
          echo "NewCircuitPeriod 10" | sudo tee -a /etc/tor/torrc
          echo "MaxCircuitDirtiness 10" | sudo tee -a /etc/tor/torrc

          # Restart Tor to apply settings
          sudo service tor restart
          sleep 5  # Wait for Tor to stabilize

      - name: Attempt to Download YouTube Video
        run: |
          while true; do
              # Get current IP address
              ip=$(torsocks curl -s https://ipinfo.io/ip)
              echo "Trying with IP: $ip"

              # Attempt to download the first YouTube video matching the search
              torsocks yt-dlp "ytsearch:sheraton hotel jeddah" --max-downloads 1

              # Check if download was successful
              if [ $? -eq 0 ]; then
                  echo "✅ Success with IP: $ip"
                  break  # Exit loop if successful
              else
                  echo "❌ Blocked with IP: $ip, retrying..."
                  sleep 10  # Wait before retrying with a new IP
              fi
          done
