name: Download YouTube Video via Tor

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  download-video:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y tor yt-dlp curl

      - name: Start Tor
        run: |
          echo "Starting Tor..."
          sudo service tor start
          sleep 10  # Give Tor time to connect

      - name: Download via SOCKS5 Proxy
        run: |
          while true; do
              # Get current IP address via Tor
              ip=$(curl -s --socks5-hostname 127.0.0.1:9050 https://ipinfo.io/ip || echo "Failed to get IP")
              echo "Trying with IP: $ip"

              # Download video using SOCKS5 proxy
              yt-dlp --proxy "socks5h://127.0.0.1:9050" "ytsearch:sheraton hotel jeddah" --max-downloads 1

              # Check if download was successful
              if [ $? -eq 0 ]; then
                  echo "✅ Success with IP: $ip"
                  break
              else
                  echo "❌ Blocked with IP: $ip, retrying..."
                  sleep 10
              fi
          done
