
name: Download YouTube Videos with Tor and Retry on Failure

on:
  push:
    branches:
      - main

jobs:
  download_videos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Tor and Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y torsocks yt-dlp tor curl

    - name: Start Tor Service
      run: |
        sudo service tor start
        sleep 5  # Give Tor time to start

    - name: Download YouTube Videos with IP retries
      run: |
        search_term="sheraton hotel jeddah"
        video_count=0
        start_time=$(date +%s)  # Get the start time in seconds

        # Retry logic
        while true; do
          # Try to download the first video
          echo "Attempting download #$((video_count + 1))..."

          # Print the public IP address from which the request is made
          ip_address=$(curl -s https://ipinfo.io/ip)
          echo "Using IP address: $ip_address"

          # Use yt-dlp with torsocks to download
          torsocks yt-dlp "ytsearch1:${search_term}" --max-downloads 1 --output "%(title)s.%(ext)s"

          # Check if yt-dlp succeeded
          if [ $? -eq 0 ]; then
            echo "Download successful, IP: $ip_address"
            video_count=$((video_count + 1))
          else
            # If download fails, continue retrying and print the failed IP
            echo "Download failed with IP: $ip_address, retrying with a new IP..."
          fi

          # Exit condition when 3 videos have been downloaded
          if [ $video_count -ge 3 ]; then
            echo "Successfully downloaded 3 videos!"
            break
          fi

          # Wait for a moment to ensure the next request uses a new IP from Tor
          sleep 10
        done
