
name: Check if First VID is Tech Niche

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours

jobs:
  check-niche:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install groq youtube-transcript-api

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
  


      - name: Run YT.py
        env:
          GROQ_API: ${{ secrets.GROQ_API }}
        run: python YT.py

      - name: Run YT1.py
        env:
          GROQ_API: ${{ secrets.GROQ_API }}
        run: python YT1.py

      - name: Commit and push if changes found (□ or ○ etc)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull --rebase origin main
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git add .
            git commit -m "Mark updates (□/○) - $(date -u)"
            git push origin main
