name: Download Videos via Tor

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  download_videos:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install dependencies (Tor + yt-dlp)
      - name: Install Tor and yt-dlp
        run: |
          sudo apt-get update
          sudo apt-get install tor curl
          sudo service tor start
          python3 -m pip install --upgrade yt-dlp

      # Step 3: Check Tor exit node IP
      - name: Check Tor exit node IP
        run: |
          echo "Checking Tor exit node IP..."
          curl --socks5 127.0.0.1:9050 https://check.torproject.org/api/ip

      # Step 4: Resolve YouTube via Tor
      - name: Resolve youtube.com via Tor
        run: |
          echo "Resolving youtube.com via Tor..."
          curl --socks5 127.0.0.1:9050 https://dns.google.com/resolve?name=www.youtube.com&type=A

      # Step 5: Search YouTube and extract links
      - name: Search YouTube for video links
        id: search
        run: |
          export http_proxy="http://127.0.0.1:8118"
          SEARCH_TERMS=(
            "Rosewood Jeddah"
            "The Ritz-Carlton, Jeddah"
            "Assila, a Luxury Collection Hotel"
            "Park Hyatt Jeddah – Marina, Club and Spa"
            "Waldorf Astoria Jeddah – Qasr Al Sharq"
            "InterContinental Jeddah"
            "Jeddah Marriott Hotel Madinah Road"
          )

          > search_results.txt  # Clear file before writing
          for term in "${SEARCH_TERMS[@]}"; do
            echo "Searching: $term"
            yt-dlp --proxy "socks5://127.0.0.1:9050" "ytsearch3:$term" --print "%(webpage_url)s" >> search_results.txt
          done

      # Step 6: Download videos with retry mechanism
      - name: Download videos
        run: |
          export http_proxy="http://127.0.0.1:8118"
          
          download_video() {
            local url="$1"
            local attempt=1
            local max_attempts=5  # Max retry attempts
            
            while [ $attempt -le $max_attempts ]; do
              echo "Attempt $attempt: Downloading $url"
              
              yt-dlp --proxy "socks5://127.0.0.1:9050" -f bestvideo+bestaudio --merge-output-format mp4 --continue --retries 5 "$url"
              
              if [ $? -eq 0 ]; then
                echo "Download successful: $url"
                return 0
              else
                echo "Download failed (attempt $attempt). Retrying..."
                attempt=$((attempt + 1))
                
                echo "Restarting Tor for new IP..."
                sudo service tor restart
                sleep 10  # Wait for a new Tor circuit
                
                echo "Checking new Tor exit node IP..."
                curl --socks5 127.0.0.1:9050 https://check.torproject.org/api/ip
              fi
            done
            echo "Failed to download $url after $max_attempts attempts."
            return 1
          }

          while IFS= read -r url; do
            download_video "$url"
          done < search_results.txt

      # Step 7: List downloaded files
      - name: List downloaded files
        run: ls -lh
