name: YouTube Auto Upload

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: '0 * * * *'  # Runs every hour (adjust if needed)

jobs:
  upload_video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client yt-dlp requests

      - name: Run YouTube Upload Script
        run: |
          python kabaju.py

      - name: Print Success
        if: success()
        run: echo "✅ Video uploaded successfully!"

      - name: Print Failure
        if: failure()
        run: echo "❌ Video upload failed."
